#ifdef __ECOS
#include "PrjCfg.h"
#include <cyg/usocket/usocket.h>
#include "WifiAppCmd.h"
#include "NVTToolCommand.h"
#include "UIInfo.h"
#include "WifiAppXML.h"

#define THIS_DBGLVL         2 //0=OFF, 1=ERROR, 2=TRACE
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          WifiAppCmd
#define __DBGLVL__          ((THIS_DBGLVL>=PRJ_DBG_LVL)?THIS_DBGLVL:PRJ_DBG_LVL)
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"
///////////////////////////////////////////////////////////////////////////////


extern WIFI_CMD_ENTRY Cmd_app[];

void UserSocket_Notify(int status,int parm)
{
    DBG_DUMP(" %d %d\r\n",status,parm);
}
UINT32 WifiApp_SendCmd(UINT32 cmd,UINT32 status)
{
    UINT32 result=0;
    static char bufArry[128];
    static UINT32 len =0;
    char *buf =bufArry;
    UINT32 sendlen=0;
    len = sprintf(buf,DEF_XML_HEAD);
    buf+=len;
    len = sprintf(buf,DEF_XML_RET,cmd,status);
    buf+=len;

    len=buf-bufArry;
    sendlen= len;
    DBG_DUMP(" %s %d\r\n",bufArry,sendlen);
    result = UserSocket_Send(bufArry,(int *)&len);
    if(sendlen!=len)
    {
        result = -1;
        DBG_ERR("sent %d error,should %d\r\n",len,sendlen);
    }
    return result;

}

INT32 WifiApp_Recv(char* addr, INT32 size)
{
    *(addr+(size))='\0';
    DBG_DUMP("WifiApp_Recv %s %d\r\n",addr,size);
    return TRUE;
}

void UserSocket_Open(void)
{

    usocket_install_obj  usocketObj={0};

    DBG_IND("open usocket\r\n");
    usocketObj.notify = UserSocket_Notify;
    usocketObj.recv = UserSocket_Recv;
    usocketObj.portNum = 3333;
    usocketObj.threadPriority = 6;
    usocketObj.sockbufSize = 40960;
    usocket_install(&usocketObj);
    // start live view daemon
    usocket_open();

}

void UserSocket_Close(void)
{
    usocket_close();
}

int UserSocket_Send(char* addr, int* size)
{
    return usocket_send(addr,size);
}

int UserSocket_Recv(char* addr, int size)
{
    *(addr+(size))='\0';
    DBG_DUMP("UserSocket_Recv %s %d\r\n",addr,size);
    return TRUE;
}

void WifiAppCmd_init(void)
{
    WifiCmd_SetExecTable(Cmd_app);
    WifiCmd_SetDefautCB((UINT32)XML_DefaultFormat);
    WifiCmd_SetEventHandle((UINT32)Ux_PostEvent);
}


WIFI_CMD_BEGIN(app)
WIFI_CMD_ITEM(WIFIAPP_CMD_CAPTURE,NVTEVT_WIFI_EXE_PHOTO_CAPTURE,(UINT32)XML_GetPictureEnd,WIFIFLAG_CAPTURE_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_CAPTURESIZE,NVTEVT_WIFI_EXE_PHOTO_SIZE,0,0, FL_PHOTO_SIZE)
WIFI_CMD_ITEM(WIFIAPP_CMD_FREE_PIC_NUM, 0,(UINT32)XML_GetFreePictureNum, 0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_RECORDING_TIME, 0, (UINT32)XML_GetMovieRecStatus, 0, FL_WIFI_MOVIE_FMT)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_REC_TRIGGER_RAWENC, NVTEVT_WIFI_EXE_MOVIE_TRIGGER_RAWENC, 0, WIFIFLAG_MOVIE_REC_RAWENC_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_GET_RAWENC_JPG, 0, (UINT32)XML_GetRawEncJpg, 0, FL_NULL)

WIFI_CMD_ITEM(WIFIAPP_CMD_RECORD,NVTEVT_WIFI_EXE_MOVIE_REC,0,WIFIFLAG_RECORD_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_REC_SIZE, NVTEVT_WIFI_EXE_MOVIE_REC_SIZE,0,0, FL_MOVIE_SIZE)
WIFI_CMD_ITEM(WIFIAPP_CMD_CYCLIC_REC      ,NVTEVT_WIFI_EXE_CYCLIC_REC   ,0,0, FL_MOVIE_CYCLIC_REC)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_HDR     ,NVTEVT_WIFI_EXE_MOVIE_HDR      ,0,0, FL_MOVIE_HDR)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_EV    ,NVTEVT_WIFI_EXE_MOVIE_EV         ,0,0, FL_EV)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOTION_DET    ,NVTEVT_WIFI_EXE_MOTION_DET     ,0,0, FL_MOVIE_MOTION_DET)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_AUDIO   ,NVTEVT_WIFI_EXE_MOVIE_AUDIO    ,0,0, FL_MOVIE_AUDIO)
WIFI_CMD_ITEM(WIFIAPP_CMD_DATEIMPRINT     ,NVTEVT_WIFI_EXE_DATEIMPRINT  ,0,0, FL_MOVIE_DATEIMPRINT)
WIFI_CMD_ITEM(WIFIAPP_CMD_MAX_RECORD_TIME   ,0 ,(UINT32)XML_GetMaxRecordTime, 0, FL_MOVIE_DATEIMPRINT)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_LIVEVIEW_SIZE, NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_SIZE, 0, 0, FL_WIFI_MOVIE_APP_PREVIEW_SIZE)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_GSENSOR_SENS, NVTEVT_WIFI_EXE_MOVIE_GSENSOR_SENS, 0, 0, FL_GSENSOR)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_AUTO_RECORDING, NVTEVT_WIFI_EXE_SET_AUTO_RECORDING, 0, 0, FL_WIFI_AUTO_RECORDING)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_REC_BITRATE    ,NVTEVT_WIFI_EXE_MOVIE_REC_BITRATE, 0,0, FL_NULL)
#if(MOVIE_LIVEVIEW==RTSP_LIVEVIEW)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_LIVEVIEW_BITRATE, NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_BITRATE, 0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_LIVEVIEW_START, NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_START,0,WIFIFLAG_PREVIEW_DONE, FL_NULL)
#endif
WIFI_CMD_ITEM(WIFIAPP_CMD_MODECHANGE,NVTEVT_WIFI_EXE_MODE,0,WIFIFLAG_MODE_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_QUERY         ,0,(UINT32)XML_QueryCmd,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_SSID    ,NVTEVT_WIFI_EXE_SET_SSID         ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_PASSPHRASE,NVTEVT_WIFI_EXE_SET_PASSPHRASE ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_DATE      ,NVTEVT_WIFI_EXE_SET_DATE       ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_TIME      ,NVTEVT_WIFI_EXE_SET_TIME       ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_POWEROFF      ,NVTEVT_WIFI_EXE_POWEROFF       ,0,0, FL_AUTO_POWER_OFF)
WIFI_CMD_ITEM(WIFIAPP_CMD_LANGUAGE      ,NVTEVT_WIFI_EXE_LANGUAGE       ,0,0, FL_LANGUAGE)
WIFI_CMD_ITEM(WIFIAPP_CMD_TVFORMAT      ,NVTEVT_WIFI_EXE_TVFORMAT       ,0,0, FL_TV_MODE)
WIFI_CMD_ITEM(WIFIAPP_CMD_FORMAT        ,NVTEVT_WIFI_EXE_FORMAT         ,0,WIFIFLAG_FORMAT_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SYSRESET      ,NVTEVT_WIFI_EXE_SYSRESET       ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_VERSION       ,0,(UINT32)XML_GetVersion,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_FWUPDATE      ,NVTEVT_WIFI_EXE_FWUPDATE       ,0,WIFIFLAG_UPDATE_DONE, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_QUERY_CUR_STATUS, 0, (UINT32)XML_QueryCmd_CurSts, 0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_FILELIST       ,0,(UINT32)XML_FileList,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_HEARTBEAT, 0, (UINT32)XML_GetHeartBeat, 0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_DISK_FREE_SPACE, 0, (UINT32)XML_GetDiskFreeSpace, 0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_RECONNECT_WIFI,NVTEVT_WIFI_EXE_RECONNECT       ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_GET_BATTERY,0       ,(UINT32)XML_GetBattery,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SAVE_MENUINFO,NVTEVT_WIFI_EXE_SAVEMENU        ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_GET_HW_CAP,0       ,(UINT32)XML_HWCapability,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_REMOVE_USER,NVTEVT_WIFI_EXE_REMOVE_USER       ,0,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_GET_CARD_STATUS, 0, (UINT32)XML_GetCardStatus,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_GET_DOWNLOAD_URL, 0, (UINT32)XML_GetDownloadURL,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_GET_UPDATEFW_PATH, 0, (UINT32)XML_GetUpdateFWPath,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SET_PIP_STYLE, NVTEVT_WIFI_EXE_PIP_STYLE, 0, 0, FL_NULL)

WIFI_CMD_ITEM(WIFIAPP_CMD_THUMB,0,(UINT32)XML_GetThumbnail,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_SCREEN,0,(UINT32)XML_GetScreen,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_MOVIE_FILE_INFO,0,(UINT32)XML_GetMovieFileInfo,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_DELETE_ONE,0,(UINT32)XML_DeleteOnePicture,0, FL_NULL)
WIFI_CMD_ITEM(WIFIAPP_CMD_DELETE_ALL,0,(UINT32)XML_DeleteAllPicture,0, FL_NULL)
WIFI_CMD_END()
#endif
