//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIWAIT_H
#define UIMENUWNDWIFIWAIT_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiWaitCtrl;//Panel type 

extern VControl UIMenuWndWiFiWait_Connect_Icon_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiWait_Connect_Icon_Status_ICON_WIFI_CONNECT,
UIMenuWndWiFiWait_Connect_Icon_Status_MAX
}UIMenuWndWiFiWait_Connect_Icon_Status_Setting;

//---------------------UIMenuWndWiFiWaitCtrl User Export---------------------------
#endif
